--27--
SELECT MADA
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV = PC.MA_NVIEN AND NV.HONV LIKE N'ĐINH'
UNION
SELECT MADA
FROM NHANVIEN AS NV, DEAN AS DA, PHONGBAN AS PB
WHERE NV.MANV = PB.TRPHG AND DA.PHONG = PB.MAPHG AND NV.HONV LIKE N'ĐINH'

--28--
SELECT NV.*
FROM NHANVIEN AS NV
WHERE NV.MANV IN (
SELECT MA_NVIEN
FROM THANNHAN AS TN
GROUP BY MA_NVIEN
HAVING COUNT(TN.TENTN) > 2
)

--29--
SELECT NV.*
FROM NHANVIEN AS NV
WHERE NV.MANV NOT IN (
SELECT DISTINCT MA_NVIEN
FROM THANNHAN AS TN
)

--30--
SELECT NV.*
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.TRPHG = NV.MANV AND NV.MANV IN(
SELECT MA_NVIEN
FROM THANNHAN AS TN
GROUP BY MA_NVIEN
HAVING COUNT(TN.TENTN) > 0
)

--31--
SELECT NV.*
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.TRPHG = NV.MANV AND NV.MANV NOT IN(
SELECT MA_NVIEN
FROM THANNHAN AS TN
WHERE TN.QUANHE LIKE N'%'
)

--32--
SELECT NV.*
FROM NHANVIEN AS NV
WHERE LUONG > (
SELECT AVG(LUONG)
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.MAPHG = NV.PHG AND PB.TENPHG LIKE N'NGHIÊN CỨU'
)

--33--
SELECT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, PB.TENPHG
FROM PHONGBAN AS PB, NHANVIEN AS NV
WHERE PB.TRPHG = NV.MANV AND PB.MAPHG IN
(
	SELECT TOP 1 NV1.PHG
	FROM NHANVIEN AS NV1
	GROUP BY NV1.PHG
	ORDER BY COUNT(NV1.MANV) DESC
)
--34--
SELECT DA.MADA
FROM DEAN AS DA
WHERE DA.MADA NOT IN
(
	SELECT PC.MADA
	FROM PHANCONG AS PC
	WHERE PC.MA_NVIEN='009'
)